version: "3.9"
services:
  rabbitmq:
    image: rabbitmq:management
    command: rabbitmq-server
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  currency_service:
    depends_on:
      - rabbitmq
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile